import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Copy, Plus, Trash2 } from 'lucide-react'
import { api, ApiError } from '../lib/api.js'
import { useAuth } from '../lib/AuthContext.jsx'

// Roles an admin can assign to a new invitation. "admin" deliberately
// absent - admin status only comes from creating a company. Kept in sync
// with NonAdminRole in backend/models/user.py.
const ROLE_OPTIONS = [
  { value: 'interviewer',    label: 'Interviewer' },
  { value: 'hiring_manager', label: 'Hiring Manager' },
  { value: 'recruiter',      label: 'Recruiter' },
]

function formatRole(role) {
  const found = ROLE_OPTIONS.find((r) => r.value === role)
  return found?.label || role || '—'
}

// Admin-only page. Shows every invitation generated by the admin's company,
// with status (active/used) and a delete button that also removes the user
// linked to the code (if any).
export default function AdminDashboardPage() {
  const { user, logout } = useAuth()
  const [invitations, setInvitations] = useState(null)  // null = loading
  const [error, setError] = useState('')
  const [generating, setGenerating] = useState(false)
  const [copiedId, setCopiedId] = useState(null)
  // Role the admin will assign to the NEXT generated code. Default mirrors
  // the most common case (interviewer) so the happy path is one click.
  const [nextRole, setNextRole] = useState('interviewer')

  const load = async () => {
    setError('')
    try {
      const data = await api.listInvitations()
      setInvitations(data)
    } catch (err) {
      if (err instanceof ApiError && err.status === 403) {
        setError('Only admins can view this page.')
      } else {
        setError(err.message)
      }
      setInvitations([])
    }
  }

  useEffect(() => { load() }, [])

  const onGenerate = async () => {
    setGenerating(true)
    setError('')
    try {
      // Role is set by the admin in the dropdown next to this button; the
      // invitee inherits it and cannot change it at signup time.
      const created = await api.createInvitation(nextRole)
      // Optimistic prepend instead of re-fetching the whole list.
      setInvitations((prev) => [created, ...(prev || [])])
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not generate code.')
    } finally {
      setGenerating(false)
    }
  }

  const onDelete = async (inv) => {
    const willKickUser = inv.status === 'used'
    const msg = willKickUser
      ? 'This code was used. Deleting it will also remove the teammate it created. Continue?'
      : 'Delete this invitation code?'
    if (!confirm(msg)) return

    try {
      await api.deleteInvitation(inv.inv_id)
      setInvitations((prev) => prev.filter((i) => i.inv_id !== inv.inv_id))
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not delete invitation.')
    }
  }

  const onCopy = async (inv) => {
    try {
      await navigator.clipboard.writeText(inv.code)
      setCopiedId(inv.inv_id)
      setTimeout(() => setCopiedId((id) => (id === inv.inv_id ? null : id)), 1500)
    } catch {
      /* clipboard blocked - silently ignore */
    }
  }

  return (
    <div className="min-h-screen bg-neutral-50/60 px-6 lg:px-10 py-8">
      <header className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight">Admin dashboard</h1>
          <p className="text-sm text-neutral-500 mt-1">
            Signed in as <span className="font-semibold text-ink">{user?.username}</span>
            {user?.email && <> · {user.email}</>}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Link to="/" className="btn-ghost !py-2 !px-4 !text-sm">Home</Link>
          <button onClick={logout} className="btn-ghost !py-2 !px-4 !text-sm">Log out</button>
        </div>
      </header>

      <section className="bg-white rounded-2xl shadow-sm">
        <div className="flex items-center justify-between px-6 py-5 border-b border-neutral-100">
          <div>
            <h2 className="text-lg font-bold text-ink">Invitation codes</h2>
            <p className="text-sm text-neutral-500">
              Generate one code per teammate. They enter it on the signup page to join your company.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <label className="flex items-center gap-2 text-sm text-neutral-600">
              <span className="font-medium">Role</span>
              <select
                value={nextRole}
                onChange={(e) => setNextRole(e.target.value)}
                disabled={generating}
                className="rounded-lg border border-neutral-200 bg-white px-3 py-2 text-sm text-ink
                           outline-none transition-all focus:border-primary-400 focus:ring-4 focus:ring-primary-100
                           disabled:opacity-60"
              >
                {ROLE_OPTIONS.map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
            </label>
            <button
              onClick={onGenerate}
              disabled={generating}
              className="btn-primary !py-2.5 !px-5 !text-sm disabled:opacity-60"
            >
              <Plus size={16} />
              {generating ? 'Generating…' : 'Generate code'}
            </button>
          </div>
        </div>

        {error && (
          <div className="mx-6 my-4 rounded-lg bg-coral-50 border border-coral-200 px-4 py-3 text-sm text-coral-700">
            {error}
          </div>
        )}

        {invitations === null ? (
          <p className="px-6 py-8 text-neutral-400">Loading…</p>
        ) : invitations.length === 0 ? (
          <p className="px-6 py-12 text-center text-neutral-400">
            No codes yet. Click <span className="font-semibold">Generate code</span> to make your first one.
          </p>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-neutral-50 text-neutral-500 text-xs uppercase tracking-wider">
              <tr>
                <th className="text-left px-6 py-3">Code</th>
                <th className="text-left px-6 py-3">Role</th>
                <th className="text-left px-6 py-3">Status</th>
                <th className="text-left px-6 py-3">Created</th>
                <th className="text-left px-6 py-3">Used</th>
                <th className="text-right px-6 py-3">Actions</th>
              </tr>
            </thead>
            <tbody>
              {invitations.map((inv) => (
                <tr key={inv.inv_id} className="border-t border-neutral-100">
                  <td className="px-6 py-3 font-mono text-ink">
                    <div className="flex items-center gap-2">
                      <span>{inv.code}</span>
                      <button
                        onClick={() => onCopy(inv)}
                        className="text-neutral-400 hover:text-primary-600"
                        title="Copy code"
                      >
                        <Copy size={14} />
                      </button>
                      {copiedId === inv.inv_id && (
                        <span className="text-xs text-mint-600 font-semibold">copied</span>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-3 text-neutral-700">{formatRole(inv.role)}</td>
                  <td className="px-6 py-3">
                    <StatusBadge status={inv.status} />
                  </td>
                  <td className="px-6 py-3 text-neutral-600">{formatDate(inv.created_at)}</td>
                  <td className="px-6 py-3 text-neutral-600">{formatDate(inv.used_at)}</td>
                  <td className="px-6 py-3">
                    <div className="flex justify-end">
                      <button
                        onClick={() => onDelete(inv)}
                        className="inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-semibold text-coral-700 hover:bg-coral-50"
                        title={inv.status === 'used' ? 'Delete code & remove teammate' : 'Delete code'}
                      >
                        <Trash2 size={14} />
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </div>
  )
}

function StatusBadge({ status }) {
  const cls =
    status === 'active'
      ? 'bg-mint-100 text-mint-700'
      : 'bg-neutral-100 text-neutral-600'
  return (
    <span className={`rounded-pill px-2.5 py-1 text-xs font-semibold ${cls}`}>
      {status}
    </span>
  )
}

function formatDate(iso) {
  if (!iso) return '—'
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return '—'
  return d.toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}
