import { useEffect, useState } from 'react'
import { Copy, Plus, Trash2 } from 'lucide-react'
import Sidebar from '../components/common/Sidebar'
import { api, ApiError } from '../lib/api.js'
import { useToast } from '../components/common/ToastContext.jsx'
import { button, card, modal, page } from '../styles/layout'

// Roles an admin can assign to a new invitation. "admin" deliberately
// absent - admin status only comes from creating a company. Kept in sync
// with NonAdminRole in backend/models/user.py.
const ROLE_OPTIONS = [
  { value: 'interviewer',    label: 'Interviewer' },
  { value: 'hiring_manager', label: 'Hiring Manager' },
  { value: 'recruiter',      label: 'Recruiter' },
]

function formatRole(role) {
  const found = ROLE_OPTIONS.find((r) => r.value === role)
  return found?.label || role || '—'
}

// Admin-only page, rendered inside the SAME app shell as every other page
// (sidebar + page main) - it used to be a bare standalone screen with its
// own Home/Logout header, which made admins feel locked out of the app.
// Shows every invitation generated by the admin's company, with status
// (active/used) and a delete button that also removes the user linked to
// the code (if any).
export default function AdminDashboardPage() {
  const toast = useToast()
  const [invitations, setInvitations] = useState(null)  // null = loading
  const [error, setError] = useState('')
  const [generating, setGenerating] = useState(false)
  const [copiedId, setCopiedId] = useState(null)
  // Role the admin will assign to the NEXT generated code. Default mirrors
  // the most common case (interviewer) so the happy path is one click.
  const [nextRole, setNextRole] = useState('interviewer')
  // Invitation queued for deletion - null when the confirm modal is closed.
  const [deleteTarget, setDeleteTarget] = useState(null)
  const [deleting, setDeleting] = useState(false)

  const load = async () => {
    setError('')
    try {
      const data = await api.listInvitations()
      setInvitations(data)
    } catch (err) {
      if (err instanceof ApiError && err.status === 403) {
        setError('Only admins can view this page.')
      } else {
        setError(err.message)
      }
      setInvitations([])
    }
  }

  useEffect(() => { load() }, [])

  const onGenerate = async () => {
    setGenerating(true)
    setError('')
    try {
      // Role is set by the admin in the dropdown next to this button; the
      // invitee inherits it and cannot change it at signup time.
      const created = await api.createInvitation(nextRole)
      // Optimistic prepend instead of re-fetching the whole list.
      setInvitations((prev) => [created, ...(prev || [])])
      toast.success(`${formatRole(created.role)} invitation code created.`)
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not generate code.')
    } finally {
      setGenerating(false)
    }
  }

  const onConfirmDelete = async () => {
    if (!deleteTarget) return
    setDeleting(true)
    try {
      await api.deleteInvitation(deleteTarget.inv_id)
      setInvitations((prev) => prev.filter((i) => i.inv_id !== deleteTarget.inv_id))
      toast.success(
        deleteTarget.status === 'used'
          ? 'Invitation deleted and its teammate removed.'
          : 'Invitation code deleted.'
      )
      setDeleteTarget(null)
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not delete invitation.')
      setDeleteTarget(null)
    } finally {
      setDeleting(false)
    }
  }

  const onCopy = async (inv) => {
    try {
      await navigator.clipboard.writeText(inv.code)
      setCopiedId(inv.inv_id)
      setTimeout(() => setCopiedId((id) => (id === inv.inv_id ? null : id)), 1500)
    } catch {
      /* clipboard blocked - silently ignore */
    }
  }

  return (
    <div className={page.shell}>
      <Sidebar />

      <main className={page.main}>
        {/* Header - same skeleton as the Jobs / Applications pages. */}
        <div className="mb-6 flex items-start justify-between">
          <div>
            <h1 className="text-4xl font-extrabold tracking-tight text-neutral-800">
              Invitations
            </h1>
            <p className="mt-1 text-xs text-neutral-400">
              Generate one code per teammate — they enter it on the signup page to join your company
            </p>
          </div>

          <div className="flex items-center gap-2">
            <label className="flex items-center gap-2 text-sm text-neutral-600">
              <span className="font-medium">Role</span>
              <select
                value={nextRole}
                onChange={(e) => setNextRole(e.target.value)}
                disabled={generating}
                className="rounded-lg border border-neutral-300 bg-neutral-0 px-3 py-2 text-sm text-neutral-700
                           outline-none transition-all focus:border-primary-400 focus:ring-4 focus:ring-primary-100
                           disabled:opacity-60"
              >
                {ROLE_OPTIONS.map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
            </label>
            <button
              onClick={onGenerate}
              disabled={generating}
              className={`flex items-center gap-2 ${button.primary} disabled:opacity-60`}
            >
              <Plus size={16} />
              {generating ? 'Generating…' : 'Generate code'}
            </button>
          </div>
        </div>

        {error && (
          <div className="mb-4 rounded-lg border border-coral-200 bg-coral-50 px-4 py-3 text-sm text-coral-700">
            {error}
          </div>
        )}

        <div className={`${card.flat} overflow-hidden`}>
          {invitations === null ? (
            <p className="px-6 py-8 text-sm text-neutral-400">Loading…</p>
          ) : invitations.length === 0 ? (
            <p className="px-6 py-12 text-center text-sm text-neutral-400">
              No codes yet. Click <span className="font-semibold">Generate code</span> to make your first one.
            </p>
          ) : (
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-neutral-50 border-b border-neutral-100">
                  {['Code', 'Role', 'Status', 'Created', 'Used', 'Actions'].map((h) => (
                    <th
                      key={h}
                      className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-neutral-500 last:text-right"
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {invitations.map((inv) => (
                  <tr key={inv.inv_id} className="border-t border-neutral-100 first:border-t-0">
                    <td className="px-6 py-3 font-mono text-neutral-800">
                      <div className="flex items-center gap-2">
                        <span>{inv.code}</span>
                        <button
                          onClick={() => onCopy(inv)}
                          className="text-neutral-400 transition-colors hover:text-primary-600"
                          title="Copy code"
                        >
                          <Copy size={14} />
                        </button>
                        {copiedId === inv.inv_id && (
                          <span className="text-xs font-semibold text-mint-600">copied</span>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-3 text-neutral-700">{formatRole(inv.role)}</td>
                    <td className="px-6 py-3">
                      <StatusBadge status={inv.status} />
                    </td>
                    <td className="px-6 py-3 text-neutral-600">{formatDate(inv.created_at)}</td>
                    <td className="px-6 py-3 text-neutral-600">{formatDate(inv.used_at)}</td>
                    <td className="px-6 py-3">
                      <div className="flex justify-end">
                        <button
                          onClick={() => setDeleteTarget(inv)}
                          className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-semibold text-coral-500 transition-colors hover:bg-coral-50 hover:text-coral-700"
                          title={inv.status === 'used' ? 'Delete code & remove teammate' : 'Delete code'}
                        >
                          <Trash2 size={14} />
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </main>

      {/* Delete confirmation - same chrome as the app's other destructive
          modals. The "used" case spells out that the teammate goes too. */}
      {deleteTarget && (
        <div className={modal.overlay}>
          <div className="bg-neutral-0 rounded-2xl w-full max-w-sm shadow-xl p-6">
            <div className="flex items-center justify-center w-12 h-12 rounded-pill bg-coral-100 mx-auto mb-4">
              <svg
                width="22" height="22" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" strokeWidth="2" className="text-coral-500"
              >
                <polyline points="3 6 5 6 21 6" /><path d="M19 6l-1 14H6L5 6" />
                <path d="M10 11v6" /><path d="M14 11v6" /><path d="M9 6V4h6v2" />
              </svg>
            </div>
            <h2 className="text-base font-bold text-neutral-800 text-center mb-1">
              Delete Invitation
            </h2>
            <p className="text-sm text-neutral-500 text-center mb-6">
              {deleteTarget.status === 'used' ? (
                <>
                  This code was already used —{' '}
                  <span className="font-semibold text-neutral-700">
                    deleting it also removes the teammate it created
                  </span>
                  . This cannot be undone.
                </>
              ) : (
                <>
                  Delete code{' '}
                  <span className="font-mono font-semibold text-neutral-700">
                    {deleteTarget.code}
                  </span>
                  ? It can no longer be used to sign up.
                </>
              )}
            </p>
            <div className="flex gap-3">
              <button
                type="button"
                onClick={() => setDeleteTarget(null)}
                disabled={deleting}
                className={`flex-1 py-2 ${button.cancel} disabled:opacity-60`}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={onConfirmDelete}
                disabled={deleting}
                className={`flex-1 py-2 ${button.danger}`}
              >
                {deleting ? 'Deleting…' : 'Delete'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function StatusBadge({ status }) {
  const cls =
    status === 'active'
      ? 'bg-mint-100 text-mint-700'
      : 'bg-neutral-100 text-neutral-600'
  return (
    <span className={`rounded-pill px-2.5 py-1 text-xs font-semibold ${cls}`}>
      {status}
    </span>
  )
}

function formatDate(iso) {
  if (!iso) return '—'
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return '—'
  return d.toLocaleString('en-AU', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
}
