name: CI

on:
  #On all pushes
  push:
  #On all pull requests
  pull_request:

jobs:
  backend:
    #Creates a fresh virtual machine
    runs-on: ubuntu-latest
    steps:
      #Clones repo onto the runner
      - uses: actions/checkout@v4

      #Setup python on the runner
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('backend/requirements*.txt') }}

      #install dependencies
      - run: pip install -r backend/requirements.txt
      #install dev dependencies (linter and test runner)
      - run: pip install -r backend/requirements-dev.txt
      #Checks linter against backend code
      - run: ruff check backend/
      #Run unit tests
      - run: python -m pytest backend/tests/

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: npm-${{ hashFiles('frontend/package-lock.json')}}
      - run: npm ci --prefix frontend
      - run: npm test --prefix frontend
      - run: npm run build --prefix frontend
